baseURL = "https://asignatura.us.es/algbas"
languageCode = "es-ES"
DefaultContentLanguage = "es"

title = "Álgebra básica"
theme = "hugo-theme-lecturenotes"
disableLiveReload = true

creatordisplayname = "Valere JEANTET"
creatoremail = "valere.jeantet@gmail.com"
lastmodifierdisplayname = "Fernando Muro"
lastmodifieremail = "fmuro@us.es"

[author]
  name = "Fernando Muro"
  homepage = "http://personal.us.es/fmuro/"

[outputs]
home = [ "HTML", "RSS", "JSON"]
